// <auto-generated />
using System;
using Admin.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Admin.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240711022308_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Admin.Domain.Entity.System.AppOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<string>("Descript")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasColumnOrder(4)
                        .HasComment("描述，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_name")
                        .HasColumnOrder(3)
                        .HasComment("操作名称");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.HasKey("Id");

                    b.ToTable("app_operation", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<Guid>("AppOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_operation_id")
                        .HasColumnOrder(4)
                        .HasComment("操作Id");

                    b.Property<Guid>("AppResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_resource_id")
                        .HasColumnOrder(3)
                        .HasComment("资源Id");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.HasKey("Id");

                    b.ToTable("app_permission", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_name")
                        .HasColumnOrder(3)
                        .HasComment("资源名称");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasColumnOrder(4)
                        .HasComment("访问地址");

                    b.HasKey("Id");

                    b.ToTable("app_resource", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasColumnOrder(4)
                        .HasComment("描述，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name")
                        .HasColumnOrder(3)
                        .HasComment("角色名称");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.HasKey("Id");

                    b.ToTable("app_role", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<Guid>("AppPermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_permission_id")
                        .HasColumnOrder(4)
                        .HasComment("权限Id");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_role_id")
                        .HasColumnOrder(3)
                        .HasComment("角色Id");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.HasKey("Id");

                    b.ToTable("app_role_permission", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar")
                        .HasColumnOrder(7)
                        .HasComment("头像");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("NickName")
                        .HasColumnType("text")
                        .HasColumnName("nickname")
                        .HasColumnOrder(6)
                        .HasComment("昵称");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password")
                        .HasColumnOrder(4)
                        .HasComment("密码");

                    b.Property<string>("QQ")
                        .HasColumnType("text")
                        .HasColumnName("qq")
                        .HasColumnOrder(10)
                        .HasComment("QQ");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt")
                        .HasColumnOrder(5)
                        .HasComment("密码");

                    b.Property<string>("Tel")
                        .HasColumnType("text")
                        .HasColumnName("telephone")
                        .HasColumnOrder(8)
                        .HasComment("手机号");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username")
                        .HasColumnOrder(3)
                        .HasComment("用户名");

                    b.Property<string>("Weixin")
                        .HasColumnType("text")
                        .HasColumnName("weixin")
                        .HasColumnOrder(9)
                        .HasComment("微信");

                    b.HasKey("Id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Admin.Domain.Entity.System.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(1)
                        .HasComment("主键");

                    b.Property<Guid>("AppRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_role_id")
                        .HasColumnOrder(4)
                        .HasComment("角色Id");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_user_id")
                        .HasColumnOrder(3)
                        .HasComment("用户Id");

                    b.Property<string>("BaseCode")
                        .HasColumnType("text")
                        .HasColumnName("base_code")
                        .HasColumnOrder(2)
                        .HasComment("编号，可空");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasColumnOrder(995)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("创建时间，默认服务器当前时间");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by")
                        .HasColumnOrder(997)
                        .HasComment("创建人Id，可空");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order")
                        .HasColumnOrder(999)
                        .HasComment("展示的顺序，顺序大的排前面 默认为0");

                    b.Property<bool>("IsActived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actived")
                        .HasColumnOrder(993)
                        .HasComment("是否启用，默认是");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasColumnOrder(994)
                        .HasComment("是否删除，默认否");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(1000)
                        .HasComment("备注");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(996)
                        .HasDefaultValueSql("NOW()")
                        .HasComment("更新时间，默认和创建时间相同");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(998)
                        .HasComment("最后更新人Id，可空");

                    b.HasKey("Id");

                    b.ToTable("app_user_role", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
